# Generated by Django 2.2.3 on 2019-07-03 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booktest', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookinfo',
            old_name='date',
            new_name='pub_date',
        ),
    ]
