# Generated by Django 2.2.3 on 2019-07-04 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booktest', '0002_auto_20190703_2159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookinfo',
            name='pub_date',
        ),
        migrations.RemoveField(
            model_name='figureinfo',
            name='book',
        ),
        migrations.RemoveField(
            model_name='figureinfo',
            name='name',
        ),
        migrations.AlterField(
            model_name='bookinfo',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='figureinfo',
            name='content',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='figureinfo',
            name='gender',
            field=models.CharField(max_length=3),
        ),
    ]
